# Site
#repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Tian Xie
title: Graduate Student in Robotics
email: txie7@jhu.edu
#website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: facespics
github_username:  txie7
# dribbble_username: jekyll
#facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: 
#linkedin_username: tianxie
# pinterest_username: jekyll
#youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Tian and I am a M.S.E student in Robotics at Johns Hopkins University. My main focus is medical robotics. I am currently working on a co-robotic ultrasound imaging system to compensate physiological motion of the lesion during biopsy. I also have interest in more general topics in robotics about kinematics, motion planning and deep learning.

# Education Section
educaton_title: Education 

# Research Projects Section
projects_title: Research Projects

# Working Experience Section
experience_title: Working Experience

# More Section
more_title: Skills
more_content: | # this will include new lines to allow paragraphs
  I have experience in:
   - MATLAB
   - C++
   - Python
   - Tensorflow
   - SolidWorks
   - ROS

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
